#include "synth/note.h"
#include "parse_notes.h"
#include "read_gpio.h"
#include "wiringPi.h"
#include <stddef.h>
#include <time.h>
#include <stdlib.h>
#include <stdio.h>

synth *synth_singleton = NULL;

#define DEBOUNCE_TIME_MS 50
volatile clock_t debounce[12] = {0};
// General handler for the pin at index pin_idx being pressed/released.
// The handler will convert pin_idx into a note, then turn that note on or off via the synthesizer interface
void pinInterruptHandler(int pin_idx)
{
    // Check if this is a spurious signal generated by the same button press event
    if (((clock() - debounce[pin_idx]) * 1000 / CLOCKS_PER_SEC) > DEBOUNCE_TIME_MS)
    {
        note n = convert(pin_idx, 5);
        int pinState = digitalRead(pin_idx);
        if (pinState == HIGH)
        {
            noteOff(n, synth_singleton);
        }
        else
        {
            noteOn(n, synth_singleton);
        }
    }
    debounce[pin_idx] = clock();
}

#define PIN_HANDLER_FUNCTION(pin_idx) \
    void pinInterrupt##pin_idx()      \
    {                                 \
        pinInterruptHandler(pin_idx); \
    }

PIN_HANDLER_FUNCTION(0)
PIN_HANDLER_FUNCTION(1)
PIN_HANDLER_FUNCTION(2)
PIN_HANDLER_FUNCTION(3)
PIN_HANDLER_FUNCTION(4)
PIN_HANDLER_FUNCTION(5)
PIN_HANDLER_FUNCTION(6)
PIN_HANDLER_FUNCTION(7)
PIN_HANDLER_FUNCTION(8)
PIN_HANDLER_FUNCTION(9)
PIN_HANDLER_FUNCTION(10)
PIN_HANDLER_FUNCTION(11)
PIN_HANDLER_FUNCTION(12)

// Macro which defines an event handler for the key at pin_idx being pressed/released.
// This allows forwarding the pin index to the event handler in a clean way,
// which is needed to be able to work with notes themselves.
#define HANDLE_PIN(pin_idx)             \
    pinMode(pin_idx, INPUT);            \
    pullUpDnControl(pin_idx, PUD_UP);   \
    wiringPiISR(pin_idx, INT_EDGE_BOTH, \
                &pinInterrupt##pin_idx)

// Register note handlers for the first 12 GPIO pins, corresponding to one octave of musical range.
// TODO: Add handler for octave key, which will be separate from the HANDLE_PIN macros
void init_gpio_handlers(synth *synth_object)
{
    wiringPiSetup();

    synth_singleton = synth_object;

    HANDLE_PIN(0);
    HANDLE_PIN(1);
    HANDLE_PIN(2);
    HANDLE_PIN(3);
    HANDLE_PIN(4);
    HANDLE_PIN(5);
    HANDLE_PIN(6);
    HANDLE_PIN(7);
    HANDLE_PIN(8);
    HANDLE_PIN(9);
    HANDLE_PIN(10);
    HANDLE_PIN(11);
    HANDLE_PIN(12);
}